name: usml
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - matplotlib
  - ipykernel
  - langchain
  - pip:
      - bitarray
      - janus-swi
      - pyswip
      - langchain
      - pyswip
      - langchain_community
      # - langchain_openai
      - python-dotenv
      - huggingface_hub
