name: usml
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - matplotlib
  - ipykernel
  - langchain
  - pip:
      - bitarray
      - janus-swi
      - pyswip
      - langchain
      - python-dotenv
      - pyswip
      - langchain_community
      - langchain_ollama
      # - langchain_openai
      # - huggingface_hub
